(() => {"use strict";
const API=window.MAALAVO_ADMIN_API_URL||localStorage.getItem("maalavo_admin_api")||"/api", $=id=>document.getElementById(id), state={token:localStorage.getItem("maalavo_admin_token")||"",editingId:null};
async function request(path,options={}){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const r=await fetch(`${API}${path}`,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Ошибка ${r.status}`);return d}
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)}
function showLogin(){$("appView").classList.add("hidden");$("loginView").classList.remove("hidden")}
function authError(e){if(/авториза|сессия|401/i.test(e.message)){state.token="";localStorage.removeItem("maalavo_admin_token");showLogin()}else toast(e.message)}
async function login(e){e.preventDefault();$("loginError").textContent="";try{const d=await request("/admin/login",{method:"POST",body:JSON.stringify({username:$("username").value.trim(),password:$("password").value})});state.token=d.token;localStorage.setItem("maalavo_admin_token",state.token);$("adminName").textContent=d.admin.username;$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");await loadAll()}catch(x){$("loginError").textContent=x.message}}
async function loadAll(){const m=await request("/admin/me");$("adminName").textContent=m.admin.username;await Promise.all([loadStats(),loadOrders(),loadProducts()])}
async function loadStats(){const {stats}=await request("/admin/stats");$("sOrders").textContent=stats.orders;$("sNew").textContent=stats.new_orders;$("sCompleted").textContent=stats.completed_orders;$("sUsers").textContent=stats.users;$("sRevenue").textContent=`${Number(stats.revenueFrom).toLocaleString("ru-RU")} ₽`}
async function loadOrders(){const {orders}=await request("/orders"),root=$("ordersList");root.innerHTML=orders.length?orders.map(o=>{const items=o.items.map(i=>`${esc(i.title)} × ${i.quantity}`).join(", ");return `<article class="order"><div class="order-head"><div><div class="order-id">${esc(o.publicId)}</div><div class="meta">${esc(o.name)} · ${esc(o.telegram)} · ${new Date(o.createdAt).toLocaleString("ru-RU")}</div></div><span class="status">${esc(o.status)}</span></div><div class="order-items">${items||"Без позиций"} · <b>${Number(o.totalFrom).toLocaleString("ru-RU")} ₽</b></div>${o.comment?`<div class="meta">${esc(o.comment)}</div>`:""}<div class="order-actions"><select data-order="${esc(o.publicId)}"><option value="new" ${o.status==="new"?"selected":""}>Новый</option><option value="processing" ${o.status==="processing"?"selected":""}>В работе</option><option value="paid" ${o.status==="paid"?"selected":""}>Оплачен</option><option value="completed" ${o.status==="completed"?"selected":""}>Выполнен</option><option value="cancelled" ${o.status==="cancelled"?"selected":""}>Отменён</option></select></div></article>`}).join(""):`<p class="muted">Заказов пока нет.</p>`;root.querySelectorAll("select[data-order]").forEach(s=>s.addEventListener("change",async()=>{try{await request(`/orders/${encodeURIComponent(s.dataset.order)}/status`,{method:"PATCH",body:JSON.stringify({status:s.value})});toast("Статус обновлён");await loadStats()}catch(e){authError(e)}}))}
async function loadProducts(){const {products}=await request("/admin/products"),root=$("productsList");root.innerHTML=products.length?products.map(p=>`<article class="product"><div><div class="product-head"><div><h3>${esc(p.title)}</h3><div class="meta">${esc(p.id)} · ${esc(p.category)} · ${p.active?"активен":"скрыт"}</div></div><strong>от ${Number(p.priceFrom).toLocaleString("ru-RU")} ₽</strong></div><p class="muted">${esc(p.description)}</p></div><div class="actions"><button class="ghost edit-product" data-id="${esc(p.id)}">Изменить</button><button class="ghost danger delete-product" data-id="${esc(p.id)}">${p.active?"Скрыть":"Удалить"}</button></div></article>`).join(""):`<p class="muted">Товаров нет.</p>`;root.querySelectorAll(".edit-product").forEach(b=>b.onclick=()=>openEditor(products.find(p=>p.id===b.dataset.id)));root.querySelectorAll(".delete-product").forEach(b=>b.onclick=async()=>{if(!confirm("Скрыть товар из магазина?"))return;try{await request(`/admin/products/${encodeURIComponent(b.dataset.id)}`,{method:"DELETE"});toast("Товар скрыт");await loadProducts()}catch(e){authError(e)}})}
function openEditor(p=null){state.editingId=p?.id||null;$("editorTitle").textContent=p?"Изменить товар":"Новый товар";$("pId").value=p?.id||"";$("pId").disabled=!!p;$("pTitle").value=p?.title||"";$("pCategory").value=p?.category||"";$("pDescription").value=p?.description||"";$("pPrice").value=p?.priceFrom??0;$("pSort").value=p?.sortOrder??0;$("pImage").value=p?.imageUrl||"";$("pActive").checked=p?.active??true;$("editorError").textContent="";$("productEditor").classList.remove("hidden")}
async function saveProduct(e){e.preventDefault();$("editorError").textContent="";const p={title:$("pTitle").value.trim(),category:$("pCategory").value.trim(),description:$("pDescription").value.trim(),priceFrom:Number($("pPrice").value),imageUrl:$("pImage").value.trim()||null,active:$("pActive").checked,sortOrder:Number($("pSort").value)};try{if(state.editingId)await request(`/admin/products/${encodeURIComponent(state.editingId)}`,{method:"PATCH",body:JSON.stringify(p)});else{p.id=$("pId").value.trim();await request("/admin/products",{method:"POST",body:JSON.stringify(p)})}$("productEditor").classList.add("hidden");toast("Товар сохранён");await loadProducts()}catch(x){$("editorError").textContent=x.message}}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("loginForm").addEventListener("submit",login);$("logout").onclick=()=>{state.token="";localStorage.removeItem("maalavo_admin_token");showLogin()};$("refreshOrders").onclick=()=>loadOrders().then(loadStats).catch(authError);$("newProduct").onclick=()=>openEditor();$("closeEditor").onclick=$("cancelEditor").onclick=()=>$("productEditor").classList.add("hidden");$("productForm").addEventListener("submit",saveProduct);document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");$("ordersTab").classList.toggle("hidden",t.dataset.tab!=="orders");$("productsTab").classList.toggle("hidden",t.dataset.tab!=="products")});if(state.token){$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");loadAll().catch(authError)}
})();
