let token='';
const $=id=>document.getElementById(id); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('toast').classList.remove('show'),1800)}
async function api(url,opt={}){opt.headers={...(opt.headers||{}),'Content-Type':'application/json'};opt.credentials='same-origin';const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка сервера');return d}
async function login(){try{const d=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:$('password').value})}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error);return x});show();}catch(e){toast(e.message)}}
async function show(){try{await api('/api/admin/me');$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadAll()}catch{token='';}}
function tab(name,el){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(name).classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));el.classList.add('active')}
async function loadAll(){const s=await api('/api/admin/stats');$('sUsers').textContent=s.users;$('sProducts').textContent=s.products;$('sOrders').textContent=s.orders;$('sRevenue').textContent=money(s.revenue);renderProducts((await api('/api/admin/products')).products);renderOrders((await api('/api/admin/orders')).orders);renderUsers((await api('/api/admin/users')).users);const a=await api('/api/admin/about');$('aboutTitle').value=a.title;$('aboutText').value=a.text}
function renderProducts(list){$('productsList').innerHTML=list.map(p=>`<div class="row"><div><b>${esc(p.name)}</b><div class="meta">${money(p.price)} · ${esc(p.category)} · ${p.active?'активен':'скрыт'}</div></div><div class="actions"><button class="btn" onclick='editProduct(${JSON.stringify(p)})'>Изменить</button><button class="btn danger" onclick="deleteProduct('${p.id}')">Скрыть</button></div></div>`).join('')||'<p style="color:var(--muted)">Товаров нет.</p>'}
async function addProduct(){try{await api('/api/admin/products',{method:'POST',body:JSON.stringify({name:$('pName').value,category:$('pCat').value,price:Number($('pPrice').value),tag:$('pTag').value,description:$('pDesc').value,image:$('pImage').value})});['pName','pPrice','pTag','pDesc','pImage'].forEach(id=>$(id).value='');toast('Товар добавлен');await loadAll()}catch(e){toast(e.message)}}
async function editProduct(p){const name=prompt('Название',p.name);if(name===null)return;const price=Number(prompt('Цена ₽',p.price));if(!Number.isFinite(price))return;const desc=prompt('Описание',p.description);if(desc===null)return;try{await api('/api/admin/products/'+encodeURIComponent(p.id),{method:'PUT',body:JSON.stringify({...p,name,price,description:desc})});toast('Сохранено');await loadAll()}catch(e){toast(e.message)}}
async function deleteProduct(id){if(!confirm('Скрыть товар из каталога?'))return;try{await api('/api/admin/products/'+encodeURIComponent(id),{method:'DELETE'});toast('Товар скрыт');await loadAll()}catch(e){toast(e.message)}}
function renderOrders(list){$('ordersList').innerHTML=list.map(o=>`<div class="row"><div><b>${esc(o.id)}</b><div class="meta">${esc(o.customer_name||'Без имени')} · ${esc(o.customer_username?'@'+o.customer_username:'')} · ${new Date(o.created_at).toLocaleString('ru-RU')}</div><div class="meta">${o.items.map(i=>esc(i.name)+' × '+i.qty).join(', ')}</div></div><div><b>${money(o.total)}</b><div class="actions"><select onchange="setStatus('${o.id}',this.value)"><option ${o.status==='pending'?'selected':''} value="pending">Ожидает</option><option ${o.status==='paid'?'selected':''} value="paid">Оплачен</option><option ${o.status==='processing'?'selected':''} value="processing">В работе</option><option ${o.status==='completed'?'selected':''} value="completed">Готов</option><option ${o.status==='cancelled'?'selected':''} value="cancelled">Отменён</option></select></div></div></div>`).join('')||'<p style="color:var(--muted)">Заказов нет.</p>'}
async function setStatus(id,status){try{await api('/api/admin/orders/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify({status})});toast('Статус обновлён');await loadAll()}catch(e){toast(e.message)}}
function renderUsers(list){$('usersList').innerHTML=list.map(u=>`<div class="row"><div><b>${esc([u.first_name,u.last_name].filter(Boolean).join(' ')||'Без имени')}</b><div class="meta">ID ${u.id} · ${esc(u.username?'@'+u.username:'нет username')}</div></div><div><b>${u.orders}</b> заказов<div class="meta">${money(u.spent)}</div></div></div>`).join('')||'<p style="color:var(--muted)">Пользователей нет.</p>'}
async function saveAbout(){try{await api('/api/admin/about',{method:'PUT',body:JSON.stringify({title:$('aboutTitle').value,text:$('aboutText').value})});toast('О проекте сохранено')}catch(e){toast(e.message)}}
show();
