(() => {
  'use strict';
  const API = String(window.MAALAVO_API_URL || '/api').replace(/\/$/, '');
  const DEVICE = () => localStorage.getItem('maalavo_device_id_v1') || '';
  const TG = () => String(window.Telegram?.WebApp?.initData || '').trim();
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const headers = () => ({'Content-Type':'application/json',...(TG()?{'X-Telegram-Init-Data':TG()}: {})});
  async function api(path,opt={}){const r=await fetch(`${API}${path}`,{...opt,headers:{...headers(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`Ошибка ${r.status}`);return d;}
  function open(title,html){const p=document.getElementById('profileSubpage'),t=document.getElementById('profileSubpageTitle'),c=document.getElementById('profileSubpageContent');if(!p||!t||!c)return;t.textContent=title;c.innerHTML=html;p.classList.add('open');p.setAttribute('aria-hidden','false');const s=document.getElementById('profileSubpageScroll');if(s)s.scrollTop=0;}
  const status=s=>({new:'Новый',in_progress:'В работе',paid:'Оплачен',completed:'Получен',cancelled:'Отменён'})[s]||s;
  async function orders(){return (await api(`/orders?deviceId=${encodeURIComponent(DEVICE())}`)).orders||[];}
  function form(o,i){return o.status==='completed'?`<form class="mr-review" data-o="${esc(o.publicId)}" data-p="${esc(i.productId)}"><b>Оцените «${esc(i.title)}»</b><div class="mr-stars">${[1,2,3,4,5].map(n=>`<button type="button" data-r="${n}">★</button>`).join('')}</div><textarea maxlength="1200" placeholder="Ваш отзыв"></textarea><button type="submit" disabled>Опубликовать</button><small class="mr-error"></small></form>`:'<div class="mr-locked">Отзыв доступен после получения товара.</div>';}
  function card(o){return `<article class="mr-order"><header><div><b>#${esc(o.publicId)}</b><small>${esc(new Date(o.createdAt).toLocaleString('ru-RU'))}</small></div><span>${esc(o.statusLabel||status(o.status))}</span></header><div class="mr-queue">${o.status==='cancelled'?'Заказ отменён':`Очередь №${Number(o.queuePosition||0)}`}</div><div class="mr-items">${(o.items||[]).map(i=>`<div><span>${esc(i.title)} × ${Number(i.quantity||1)}</span><b>${Number(i.priceFrom||0).toLocaleString('ru-RU')} ₽</b></div>`).join('')}</div><strong class="mr-total">Итого: ${Number(o.totalFrom||0).toLocaleString('ru-RU')} ₽</strong><div>${(o.items||[]).map(i=>form(o,i)).join('')}</div></article>`;}
  async function showOrders(title='Мои заказы',filter=()=>true){try{const list=(await orders()).filter(filter);open(title,list.length?`<div class="mr-list">${list.map(card).join('')}</div>`:'<div class="mr-empty"><b>Пока пусто</b><span>Здесь появятся ваши заказы.</span></div>');}catch(e){open(title,`<div class="mr-empty">${esc(e.message)}</div>`);}}
  function cart(){let ids=[];try{ids=JSON.parse(localStorage.getItem('maalavo_cart_v5')||'[]')}catch{}const ps=[...document.querySelectorAll('#products .product')];const items=ids.map(id=>ps.find(p=>p.dataset.id===id)).filter(Boolean);if(!items.length){open('Корзина','<div class="mr-empty"><b>Корзина пуста</b><span>Добавьте товар из каталога.</span></div>');return;}open('Корзина',`<div class="mr-cart">${items.map(p=>`<div><img src="${esc(p.querySelector('.product-image img')?.src||'')}" alt=""><span><b>${esc(p.querySelector('.product-title')?.textContent.trim()||p.dataset.id)}</b><small>${esc(p.querySelector('.price')?.textContent.trim()||'')}</small></span><button data-remove="${esc(p.dataset.id)}">Удалить</button></div>`).join('')}</div>`);}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-screen]');if(!b)return;const t=b.dataset.profileScreen;if(!['orders','purchases','status','feedback','cart'].includes(t))return;e.preventDefault();e.stopImmediatePropagation();if(t==='cart')cart();else if(t==='purchases')showOrders('Мои покупки',o=>o.status==='completed');else if(t==='feedback')showOrders('Оценить заказ',o=>o.status==='completed');else showOrders(t==='status'?'Статус заказа':'Мои заказы');},true);
  document.addEventListener('click',e=>{const r=e.target.closest('[data-remove]');if(r){let ids=[];try{ids=JSON.parse(localStorage.getItem('maalavo_cart_v5')||'[]')}catch{}localStorage.setItem('maalavo_cart_v5',JSON.stringify(ids.filter(x=>x!==r.dataset.remove)));cart();return;}const s=e.target.closest('.mr-stars button');if(s){const f=s.closest('form');const n=Number(s.dataset.r);f.dataset.rating=n;f.querySelectorAll('.mr-stars button').forEach(x=>x.classList.toggle('active',Number(x.dataset.r)<=n));f.querySelector('button[type=submit]').disabled=false;}},false);
  document.addEventListener('submit',async e=>{const f=e.target.closest('.mr-review');if(!f)return;e.preventDefault();const err=f.querySelector('.mr-error');try{await api('/reviews',{method:'POST',body:JSON.stringify({deviceId:DEVICE(),orderId:f.dataset.o,productId:f.dataset.p,rating:Number(f.dataset.rating),text:f.querySelector('textarea').value.trim()})});f.outerHTML='<div class="mr-success">Отзыв опубликован. Спасибо! ❤️</div>';}catch(x){err.textContent=x.message;}},false);
  let currentProduct='';
  document.addEventListener('click',e=>{const p=e.target.closest('.product');if(p)currentProduct=p.dataset.id||'';},true);
  const observer=new MutationObserver(()=>{const page=document.getElementById('productPage');if(!page?.classList.contains('open')||!currentProduct)return;const c=page.querySelector('.product-page-content');if(!c||c.querySelector('.mr-reviews'))return;const box=document.createElement('section');box.className='mr-reviews';c.appendChild(box);api(`/products/${encodeURIComponent(currentProduct)}/reviews`).then(d=>{box.innerHTML=`<h3>Отзывы покупателей</h3><small>${d.stats?.count?`${Number(d.stats.average).toFixed(1)} / 5 · ${d.stats.count}`:'Пока нет отзывов'}</small>${(d.reviews||[]).map(r=>`<article><b>${esc(r.displayName||'Покупатель')}</b><span>${'★'.repeat(Number(r.rating))}${'☆'.repeat(5-Number(r.rating))}</span><small>${esc(new Date(r.createdAt).toLocaleDateString('ru-RU'))}</small><p>${esc(r.text||'')}</p></article>`).join('')||'<p>Покупатели ещё не оставляли отзывов.</p>'}`}).catch(()=>{box.innerHTML='<p>Отзывы временно недоступны.</p>'});});
  observer.observe(document.body,{subtree:true,attributes:true,attributeFilter:['class']});
  setInterval(()=>{const p=document.getElementById('profileSubpage');if(!p?.classList.contains('open'))return;const t=document.getElementById('profileSubpageTitle')?.textContent;if(t==='Мои заказы'||t==='Статус заказа'||t==='Мои покупки'||t==='Оценить заказ')showOrders(t,t==='Мои покупки'||t==='Оценить заказ'?o=>o.status==='completed':()=>true);},10000);
  const st=document.createElement('style');st.textContent='.mr-list{display:grid;gap:12px}.mr-order{padding:15px;border:1px solid #ffffff14;border-radius:16px;background:#ffffff06}.mr-order header{display:flex;justify-content:space-between;gap:10px}.mr-order header div{display:grid;gap:4px}.mr-order header small,.mr-order small{color:#ffffff88}.mr-order header>span{padding:5px 9px;border-radius:999px;background:#ffffff12;font-size:12px}.mr-queue{margin:9px 0;color:#ffffff88;font-size:13px}.mr-items{display:grid;gap:6px}.mr-items>div{display:flex;justify-content:space-between}.mr-total{display:block;margin-top:10px;padding-top:10px;border-top:1px solid #ffffff12}.mr-review{margin-top:12px;padding-top:12px;border-top:1px solid #ffffff12;display:grid;gap:8px}.mr-stars{display:flex;gap:3px}.mr-stars button{background:none;border:0;color:#ffffff35;font-size:27px;padding:0}.mr-stars button.active{color:#ffd166}.mr-review textarea{min-height:70px;background:#0003;color:inherit;border:1px solid #ffffff18;border-radius:10px;padding:10px}.mr-review>button[type=submit]{border:0;border-radius:10px;padding:10px;background:#fff;color:#111;font-weight:700}.mr-review>button:disabled{opacity:.45}.mr-error{color:#ff9696}.mr-success{margin-top:12px;color:#8ff0ba}.mr-locked{margin-top:12px;color:#ffffff88;font-size:13px}.mr-empty{text-align:center;padding:30px;color:#ffffff88;display:grid;gap:7px}.mr-empty b{color:#fff}.mr-cart{display:grid;gap:10px}.mr-cart>div{display:grid;grid-template-columns:52px 1fr auto;gap:10px;align-items:center;padding:10px;border:1px solid #ffffff12;border-radius:14px}.mr-cart img{width:52px;height:52px;border-radius:10px;object-fit:cover}.mr-cart span{display:grid;gap:4px}.mr-cart button{border:1px solid #ff777733;background:#ff555510;color:#ff9c9c;border-radius:9px;padding:7px}.mr-reviews{margin-top:24px;padding-top:18px;border-top:1px solid #ffffff12}.mr-reviews h3{margin:0 0 5px}.mr-reviews>small{color:#ffffff88}.mr-reviews article{margin-top:10px;padding:11px;border-radius:12px;background:#ffffff06}.mr-reviews article span{float:right;color:#ffd166}.mr-reviews article small{display:block;color:#ffffff66;margin-top:4px}.mr-reviews article p{white-space:pre-wrap;color:#ffffffc0;line-height:1.4}';document.head.appendChild(st);
})();
